Dwarf-Therapist/Dwarf-Therapist

README.rst
doc/CMakeLists.txt

Building the manual requires opt-in using the BUILD_MANUAL cmake option.

Make PDF manual compilation optional

---

src/activityevent.cpp
src/dfinstance.cpp
src/dwarf.cpp
src/dwarfmodel.cpp
src/gamedatareader.cpp
src/gamedatareader.h
src/gridviewdialog.cpp
src/highestmoodcolumn.cpp
src/roledialog.cpp
src/scriptdialog.cpp
src/skill.cpp
src/skill.h
src/skillcolumn.cpp
src/uberdelegate.cpp
src/unitemotion.cpp

Changed default of get_skill_name to noun, some use may need to change back to name.
Known uses of skill names/nouns:
| where                                                    | before          | now                    |
| -------------------------------------------------------- | --------------- | ---------------------- |
| dwarf tool-tip (highest moodable skill)  	               | noun (or empty) | noun (or Craftsdwarf)  |
| skill name (used in dwarf tool-tip/details/...)          | noun            | noun                   |
| caste description: bonuses                               | name            | noun                   |
| custom role dialog editor                                  | name            | noun                   |
| trait "Can(not) be a %2" …

Skill name changes

---

src/dwarftherapist.cpp
src/mainwindow.cpp

Both commits fixes different issues with the paths to find data when doing `make install`.
https://github.com/Dwarf-Therapist/Dwarf-Therapist/commit/d8b63f40e8738486c295d847d517237315318eb6: On Linux the manual is installed into `/usr/share/doc/dwarftherapist`. The comment already indicated that this directory should be in the path but it wasn't. Didn't want to remove the existing line though in case it would break something
https://github.com/Dwarf-Therapist/Dwarf-Therapist/commit/b843d2104c8f9f43baf7e43345a1b6d0c1de771c: Memory layouts are installed into `/usr/share/dwarftherapist/memory_layouts`. However Dwarf Therapist on Linux is looking for them in different directories called `dwarf-therapist`. This fixes it.

Linux fix paths

---

src/viewmanager.cpp

This fixes bug with Qt5 when KDE is installed:
https://bugreports.qt.io/browse/QTBUG-47696
Effectively if you have KDE installed your tabs will have ampersand in it's title which breaks string comparison.

Compare view names instead of tab text

---

.travis.yml

This reverts commit 33b1faa5703bacea93aa45f1d57c8f87427fbbc1.
fix #41

Revert "travis: use Qt 5.7 for OSX builds"

---

src/gridview.cpp
src/gridviewdialog.cpp
src/gridviewdialog.h
src/viewcolumnset.cpp

Search items by pointer instead of names, in case of name collision.
fix #21

gridviewdialog: use pointer as user data in QStandardItemModel

---

src/mainwindow.cpp
src/mainwindow.ui

Old help actions linked to Splinterz's forum thread and paypal donation.
Forum thread link is updated and "Donate" action is hidden.
fix #66

Update help links

---

src/dfinstanceosx.h
src/dfinstanceosx.mm

fix #81 
@ifreund Can you confirm this is still good?

dfinstanceosx: use seteuid to temporarily drop privileges

---

src/statetableview.cpp

Fix a bug where unassignable citizens could be assigned to a squad if they were part of a multi selection.
fix #76

Check can_assign_military when assigning multiple dwarves to a squad

---

src/dwarf.cpp
src/optionsmenu.cpp
src/optionsmenu.ui

Related to #97 
This is draft version, it work, but can be improved.

Allow customize skills ui in tooltip

---

src/dwarf.cpp

Stress can be under ecstatic threshold when using a wrong game_data.ini.
Ignore ecstatic threshold so the happiness level does not go beyond
that.

Fix a crash with out of bound stress level

---

src/dwarf.cpp

Animals usually don't have a second columns. Remove it when it is empty,
so there is not a big empty space on the right of the tooltip.
fix #110

Remove toolitip second columns when it is empty

---

src/dwarf.h

Replaced enum argument with int so the value can be passed from scripts.
Fix #108

Fix usage of Dwarf::attribute and Dwarf::attribute_maximum in scripts

---

src/itemsubtype.h

IS_ARMOR and IS_CLOTHING flags where inverted in
ce9a403d5541858501be5bf33bddd6096848be77. This fixes compatiblity with
older versions but breaks roles and columns created since the error was
made.
fix #118

Fix IS_ARMOR and IS_CLOTHING flags

---

resources/game_data.ini

The names were inconsistent with other hauling labors.
Fix #159

Rename Trade Goods/Water Hauling labors

---

src/dfinstanceosx.mm
src/dwarftherapist.cpp
src/dwarftherapist.h
src/mainwindow.cpp
src/mainwindow.h
src/mainwindow.ui
src/standardpaths.cpp
src/standardpaths.h
src/truncatingfilelogger.cpp
src/truncatingfilelogger.h

New default location are:
- Windows: %APPDATA%/Local/Dwarf Therapist/dwarftherapist.log
- macOS: ~/Library/Logs/io.github.dwarf-therapist/dwarftherapist.log
- Linux: no log file
Portable/developer modes stores the log in the application directory.
Log path can be overriden using the "--log=<path>" option.

Move log file to a standard path

---

src/dwarftherapist.cpp
src/optionsmenu.cpp
src/optionsmenu.ui

Let choose the style from the option menu and store it in the settings.
In the current state, if the stored style value is not found in the QStyleFactory keys, the combo box may not be set accordingly and the style may change when accepting the option dialog.

Add style option

---

src/superlaborcolumn.cpp

Too many decimals prevents the rating from fitting in the grid view.
http://www.bay12forums.com/smf/index.php?topic=168411.msg8099117#msg8099117

Round super labor display rating

---

src/dwarftherapist.cpp
src/notifierwidget.cpp

During MainWindow constructor m_main_window is not set but
get_main_window may still be called.
fix #237

Make DwarfTherapist::get_main_window safer

---

src/dfinstanceosx.h
src/dfinstanceosx.mm
src/standardpaths.cpp

The reason settings aren't saved properly in OSX is because the config
file ends up getting owned by root. Changing the ownership in between
runs doesn't work because QT's default method of writing a file creates
a temp file (which will be owned by root if the settings sync when
running as root) which it then copies over the original file. We can fix
this by simply changing the file ownership to the current UID and GID
after we construct a `QSettings` object, which is when this generally
seems to happen.
Fixes #72.

Set correct file ownership for Dwarf Therapist.ini in OSX

---

src/dwarf.cpp
src/optionsmenu.cpp

It is not known what it does in the current version. Hide it until the proper wording is found.
replaces #262
@Putnam3145 do you agree with this?

Hide commitment in sexual orientation details

---

CMakeLists.txt

CMake versions < 3.5 will be deprecated in the next CMake release. If you bump CMake version to at least 3.5, everything still compiles, it seems, and it resolves the deprecation warnings when compiling.

Bump CMake minimal required version to 3.5
