src/dwarf.cpp

@feelotraveller Is that what you wanted?

Dwarf tool-tip style

---

src/histfigure.cpp

Kill count fix

---

src/rotatedheader.cpp

fix #28 
Need checking if 0 is too low and create regression with other Qt versions.

Set minimum grid view header width

---

src/dfinstancelinux.cpp
src/histfigure.cpp

fix http://www.bay12forums.com/smf/index.php?topic=168411.msg7642022#msg7642022

linux fixes + reputation/fake_identity bug

---

CMakeLists.txt
osx/MacOSXBundleInfo.plist.in

Add support of retina display in osx

---

BUILDING.md
README.rst

@Senjai I will wait for you to finish the macOS instructions (#27) and I will move them in BUILDING.rst.

Add BUILDING.rst for detailed building instructions

---

src/dfinstance.cpp
src/dfinstance.h
src/selectparentlayoutdialog.cpp
src/viewmanager.cpp

DT used to stop at the first memory_layouts/gridviews directory found.

Search data from all search paths

---

src/mainwindow.cpp

CSV export was trying to print rows for creatures that were initialized
in the view column cells because of the animal filter.
Fixes http://www.bay12forums.com/smf/index.php?topic=168411.msg7683235#msg7683235

Fix csv export crashing

---

src/dwarf.cpp

Check mercenaries based on occupation

---

.travis.yml
.travis/linux/deploy.sh

Fix #61 
[test build](https://github.com/cvuchener/Dwarf-Therapist/releases/download/untagged-12db3edc40c1da8efac9/DwarfTherapist--linux-x86_64.AppImage)

travis: Bundle libstdc++ as optional library

---

src/mainwindow.cpp
src/mainwindow.h

Add retry button to lost connection dialog.

---

src/dfinstanceosx.mm

Fixes #79 
Many thanks to @cvuchener

Fix macOS VM_TYPE_OFFSET

---

resources/game_data.ini
src/dwarf.cpp
src/gamedatareader.cpp
src/gamedatareader.h

Made happiness threshold configurable through game_data.ini and use new
thresholds for DF 0.44.10 (divided by ten).

Update happiness threshold for DF 0.44.10

---

src/dwarf.cpp

I took your code as the basis, compared it to my old one.
The code matched completely.
Ref to #94

Improve labor tooltip

---

src/importexportdialog.cpp

Only import selected professions.
fix #95

Fix importing custom professions

---

src/dfinstancelinux.cpp

Leave the x86_64 red zone untouched.
Align stack on 16 bytes.
It might fix some rare crashes.

dfinstancelinux: fix call convention

---

src/scriptdialog.cpp
src/scriptdialog.h
src/scriptdialog.ui

Script editor fix

---

src/dwarf.h
src/dwarfmodel.cpp
src/scriptdialog.cpp

http://www.bay12forums.com/smf/index.php?topic=168411.msg7824867#msg7824867

Military filters

---

README.rst

Add AUR package to README

---

BUILDING.md
CMakeLists.txt
src/dwarftherapist.cpp
src/standardpaths.cpp
src/standardpaths.h

Make it easier to use Dwarf Therapist without installation for developers.

Add developer mode

---

src/defaultroleweight.cpp
src/defaultroleweight.h
src/dfinstance.cpp
src/dwarf.cpp
src/dwarfstats.cpp
src/dwarfstats.h
src/optionsmenu.cpp
src/optionsmenu.ui
src/preferencecolumn.cpp
src/role.cpp
src/role.h
src/rolecalcbase.cpp
src/rolecalcbase.h
src/roledialog.cpp
src/roledialog.h
src/roledialog.ui
src/rolemodel.cpp
src/rolemodel.h

Alternative to #126 with fixed old role calculations instead of all new ones.

Add needs for roles (version 2)

---

src/about.ui

Fix about dialog readability with different styles.

About style fix

---

src/languages.cpp
src/languages.h

Prevents crash when invalid data is read from DF.

languages: check if word index is out of bound

---

src/dwarf.cpp
src/dwarf.h
src/scriptdialog.cpp

Also change default "base" parameter to true for easier filtering. And
fix caste_* name in script dialog documentation.

Make Dwarf::race_name invokable from scripts

---

src/dfinstanceosx.mm
src/dwarftherapist.cpp

This reverts commit e1fcd558a6649620a9792096ab651f5ebb2e9f26.
fix #177

Revert "Drop root privileges earlier on macOS"

---

src/dwarf.cpp
src/dwarfmodel.cpp
src/dwarfmodel.h
src/optionsmenu.cpp
src/optionsmenu.ui
src/unitwound.cpp

fix #189 
Now the question is: does it show too much information on animal health?
Animals were harmed during the making of the tests.
A yak got bruised in a gentle cave-in, but this kind of wound is visible in-game. I need a protocol that would create wounds requiring diagnosis. Maybe a higher fall would do? Any advice from expert torturers?

Animal health

---

share/memory_layouts/linux/v0.47.01_linux32.ini
share/memory_layouts/linux/v0.47.01_linux64.ini
share/memory_layouts/linux/v0.47.02_linux32.ini
share/memory_layouts/linux/v0.47.02_linux64.ini
share/memory_layouts/linux/v0.47.03_linux32.ini
share/memory_layouts/linux/v0.47.03_linux64.ini
share/memory_layouts/linux/v0.47.04_linux32.ini
share/memory_layouts/linux/v0.47.04_linux64.ini
share/memory_layouts/osx/v0.47.01_osx32.ini
share/memory_layouts/osx/v0.47.01_osx64.ini
share/memory_layouts/osx/v0.47.02_osx32.ini
share/memory_layouts/osx/v0.47.02_osx64.ini
share/memory_layouts/osx/v0.47.03_osx32.ini
share/memory_layouts/osx/v0.47.03_osx64.ini
share/memory_layouts/osx/v0.47.04_osx32.ini
share/memory_layouts/osx/v0.47.04_osx64.ini
share/memory_layouts/windows/v0.47.01_graphics_win32.ini
share/memory_layouts/windows/v0.47.01_graphics_win64.ini
share/memory_layouts/windows/v0.47.02_graphics_win32.ini
share/memory_layouts/windows/v0.47.02_graphics_win64.ini
share/memory_layouts/windows/v0.47.03_graphics_win32.ini
share/memory_layouts/windows/v0.47.03_graphics_win64.ini
share/memory_layouts/windows/v0.47.04_graphics_win32.ini
share/memory_layouts/windows/v0.47.04_graphics_win64.ini

fix focus offset for 0.47

---

.travis/linux/deploy.sh

Add AppRun in linux AppImage

---

.travis.yml
CMakeLists.txt
src/dfinstance.cpp
src/dfinstance.h
src/dftime.cpp
src/dftime.h
src/dwarf.cpp
src/dwarf.h
src/dwarfmodel.cpp
src/gamedatareader.cpp
src/gamedatareader.h
src/mainwindow.cpp
src/squad.cpp
src/unitemotion.cpp
src/unitemotion.h

Time refactor + date in window title

---

.travis.yml
.travis/osx/install_deps.sh

Fix macOS deployment target variable

---

src/dfinstance.h
src/dfinstancelinux.cpp
src/dfinstanceosx.mm
src/rolepreferencemodel.cpp

Fix attaching when loading role preferences

---

resources/game_data.ini
src/dwarf.cpp
src/profession.h

Fix professions that should not be eligible for squads

---

src/memorylayoutmanager.cpp

Fix creating new memory layouts and reporting supported versions

---

.github/workflows/build.yml
CMakeLists.txt

Replace top-level source/binary dirs with current ones.
Replace #256

cmake: fix some paths

---

src/dfinstance.cpp
src/dfinstance.h

Reload identity vector when refreshing data

---

src/dwarf.cpp
src/optionsmenu.cpp
src/optionsmenu.ui

Add top skill only option for tooltip

---

src/dwarf.cpp
src/dwarf.h

updated CaveAdapt index
removed no longer used OnBreak

Fix misc traits

---

share/memory_layouts/linux/v0.50.10-classic_linux64.ini
share/memory_layouts/linux/v0.50.10-itch_linux64.ini
share/memory_layouts/linux/v0.50.10-steam_linux64.ini
share/memory_layouts/linux/v0.50.11-classic_linux64.ini
share/memory_layouts/linux/v0.50.11-itch_linux64.ini
share/memory_layouts/linux/v0.50.11-steam_linux64.ini
share/memory_layouts/windows/v0.50.04-steam_win64.ini
share/memory_layouts/windows/v0.50.05-steam_win64.ini
share/memory_layouts/windows/v0.50.07-classic_win64.ini
share/memory_layouts/windows/v0.50.07-itch_win64.ini
share/memory_layouts/windows/v0.50.07-steam_win64.ini
share/memory_layouts/windows/v0.50.08-classic_win64.ini
share/memory_layouts/windows/v0.50.08-itch_win64.ini
share/memory_layouts/windows/v0.50.08-steam_win64.ini
share/memory_layouts/windows/v0.50.09-classic_win64.ini
share/memory_layouts/windows/v0.50.09-itch_win64.ini
share/memory_layouts/windows/v0.50.09-steam_win64.ini
share/memory_layouts/windows/v0.50.10-classic_win64.ini
share/memory_layouts/windows/v0.50.10-itch_win64.ini
share/memory_layouts/windows/v0.50.10-steam_win64.ini
share/memory_layouts/windows/v0.50.11-classic_win64.ini
share/memory_layouts/windows/v0.50.11-itch_win64.ini
share/memory_layouts/windows/v0.50.11-steam_win64.ini
src/dwarf.cpp
src/dwarf.h

Fix equipment update for military dwarves

---

src/dwarf.cpp

Accept units without hf id as possible citizens
